### ISSUE TITLE
Input Field Validations Error

### ISSUE THREAD

**Issue by shihababrar** [awran5/react-material-ui-step-form#2]
The validation is not working properly. Example: email field is showing error but we do get access to the NEXT button.

**Comment by awran5** [comment]
Hi @shihababrar .. Actually it was intended to be just a basic validation (only checks for field length) because there are so many ways to validate the email field. If you like, you could add more advanced email validation like so..

1. Edit the **FirstStep.js** page and add this variable just after the *import* section:

```js
// Basic regex email validation
const isEmail = RegExp(/^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}$/i);
```

2. And include this into the `isEmpty`  variable: 

```js
  const isEmpty =
    firstName.length > 0 &&
    lastName.length > 0 &&
    gender.length > 0 &&
    email.length > 0 &&
    isEmail.test(email); // add this
```
Here is a working [sandbox](https://codesandbox.io/s/react-material-ui-step-form-ui788?file=/src/components/FirstStep.js) example.

**Comment by shihababrar** [comment]
> Hi @shihababrar .. Actually it was intended to be just a basic validation (only checks for field length) because there are so many ways to validate the email field. If you like, you could add more advanced email validation like so..
> 
> 1. Edit the **FirstStep.js** page and add this variable just after the _import_ section:
> 
> ```js
> // Basic regex email validation
> const isEmail = RegExp(/^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}$/i);
> ```
> 
> 1. And include this into the `isEmpty`  variable:
> 
> ```js
>   const isEmpty =
>     firstName.length > 0 &&
>     lastName.length > 0 &&
>     gender.length > 0 &&
>     email.length > 0 &&
>     isEmail.test(email); // add this
> ```
> 
> Here is a working [sandbox](https://codesandbox.io/s/react-material-ui-step-form-ui788?file=/src/components/FirstStep.js) example.

Yeah Cool.
Thanks.
